import {
	SITE_PAGE_READ_PARSING_ERROR_CODE,
	SETTINGS_READ_PARSING_ERROR_CODE,
	THEME_READ_PARSING_ERROR_CODE,
	GLOBAL_ELEMENT_PARSING_ERROR_CODE,
	THEME_READ_SIZE_ERROR_CODE,
	SITE_PAGE_READ_PARSING_ERROR_MESSAGE,
	SETTINGS_READ_PARSING_ERROR_MESSAGE,
	THEME_READ_PARSING_ERROR_MESSAGE,
	GLOBAL_ELEMENT_PARSING_ERROR_MESSAGE,
	THEME_READ_SIZE_ERROR_MESSAGE,
	GENERIC_ERROR_CODE,
	GENERIC_ERROR_MESSAGE,
} from './constants.js';

export type ParseErrorCode = typeof SITE_PAGE_READ_PARSING_ERROR_CODE
	| typeof SETTINGS_READ_PARSING_ERROR_CODE
	| typeof THEME_READ_PARSING_ERROR_CODE
	| typeof GLOBAL_ELEMENT_PARSING_ERROR_CODE;

export type SizeErrorCode = typeof THEME_READ_SIZE_ERROR_CODE;

export type GenericErrorCode = typeof GENERIC_ERROR_CODE;

export type ErrorCode = ParseErrorCode | SizeErrorCode | GenericErrorCode;

export type ParseErrorMessage = typeof SITE_PAGE_READ_PARSING_ERROR_MESSAGE
	| typeof SETTINGS_READ_PARSING_ERROR_MESSAGE
	| typeof THEME_READ_PARSING_ERROR_MESSAGE
	| typeof GLOBAL_ELEMENT_PARSING_ERROR_MESSAGE;

export type SizeErrorMessage = typeof THEME_READ_SIZE_ERROR_MESSAGE;

export type GenericErrorMessage = typeof GENERIC_ERROR_MESSAGE;

export type ErrorMessage = ParseErrorMessage | SizeErrorMessage | GenericErrorMessage;
